services:
  server:
    image: docker.io/maurohoracio/oxibooru_server:latest
    container_name: server
    depends_on:
      - sql
    environment:
      POSTGRES_HOST: sql
      POSTGRES_USER: max
      POSTGRES_PASSWORD: serenata
      POSTGRES_DB: oxibooru
      POSTGRES_PORT: 5432
      PORT: 3000
    volumes:
      - "oxibooru_data:/data:Z"
      - "/home/mauro/Documentos/Develop/oxibooru-jxl-support/server/config.toml:/opt/app/config.toml:ro"
    ports:
      - "6666:6666"
    stop_signal: SIGINT
    restart: unless-stopped

  client:
    image: docker.io/maurohoracio/oxibooru_client:latest
    container_name: client
    depends_on:
      - server
    environment:
      BACKEND_HOST: server
    volumes:
      - "oxibooru_data:/data:ro"
    ports:
      - "8099:80"
    restart: unless-stopped
  sql:
    image: docker.io/postgres:16-alpine
    container_name: sql
    restart: unless-stopped
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: serenata
      POSTGRES_DB: oxibooru
    volumes:
      - "oxibooru_postgres:/var/lib/postgresql/data:Z"
    ports:
      - "5432:5432"
volumes:
  oxibooru_data:
  oxibooru_postgres:
